version: "2"

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:3.2.1
    ports:
      - "2181:2181"
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:3.2.1
    hostname: kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CREATE_TOPICS: "readings:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  schema_registry:
    container_name: schema_registry
    image: confluentinc/cp-schema-registry:3.2.1
    ports:
      - "8081:8081"
    links:
      - zookeeper
      - kafka
    depends_on:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema_registry

  kafka-cli:
    container_name: kafka-cli
    image: taion809/kafka-cli
    working_dir: /opt/kafka/bin
    # dummy command just to give the container a PID 1 and keep it running
    command: "tail -f /var/log/bootstrap.log > /dev/null 2>&1"
    links:
      - kafka
      - zookeeper

  rest_producer:
    container_name: rest_producer
    image: lombardo/kafka-rest-producer:latest
    ports:
      - "8080:8080"
    links:
      - kafka

  basic_stream_processor:
    container_name: basic_stream_processor
    image: lombardo/basic_stream_processor:latest
    links:
      - kafka
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092

  kafka_connect:
    container_name: kafka_connect
    image: confluentinc/cp-kafka-connect:3.2.1
    ports:
      - "8083:8083"
    links:
      - zookeeper
      - kafka
    depends_on:
      - zookeeper
      - kafka
    environment:
      # networking
      CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka_connect"
      CONNECT_REST_PORT: "8083"
      # kafka
      CONNECT_GROUP_ID: "readings-connect"
      CONNECT_CONFIG_STORAGE_TOPIC: "readings-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "readings-offset"
      CONNECT_STATUS_STORAGE_TOPIC: "readings-status"
      # convertors
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      # these are for json conversion...stashing for later
        # CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
        # CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
    volumes:
      - ./readings:/tmp/readings
